const dollieBlairAuthor = {
  name: 'Dollie Blair',
  avatar: './avatars/user2.png',
  link: '/channel/dollie-blair',
  subscribers: '2.3m',
  feed: [
    {
      title: 'A Brief History Of Creation Very Long Title',
      author: 'Dollie Blair',
      views: '80k views',
      date: '3 days ago',
      duration: '4:15',
      imgSrc: './images/cover1.png',
      link: '/',
    },
    {
      title: 'Selecting The Right Hotel',
      author: 'Dollie Blair',
      views: '123k views',
      date: '1 month ago',
      duration: '8:00',
      imgSrc: './images/cover2.png',
      link: '/',
    },
    {
      title: 'Asteroids',
      author: 'Dollie Blair',
      views: '43k views',
      date: '12 days ago',
      duration: '5:32',
      imgSrc: './images/cover3.png',
      link: '/',
    },
    {
      title: 'Telescopes 101',
      author: 'Dollie Blair',
      views: '11k views',
      date: '6 months ago',
      duration: '6:40',
      imgSrc: './images/cover4.png',
      link: '/',
    },
    {
      title: 'Medical Care Is Just',
      author: 'Dollie Blair',
      views: '18k views',
      date: '2 days ago',
      duration: '1:45',
      imgSrc: './images/cover5.png',
      link: '/',
    },
    {
      title: 'Moon Gazing',
      author: 'Dollie Blair',
      views: '67k views',
      date: '4 months ago',
      duration: '2:12',
      imgSrc: './images/cover6.png',
      link: '/',
    },
  ],
}

export default dollieBlairAuthor
