const foodAndDrinkAuthor = {
  name: 'Food & Drink',
  avatar: './avatars/user8.png',
  link: '/channel/food-and-drink',
  subscribers: '1.1m',
  feed: [
    {
      title: 'Astronomy Or Astrology',
      author: 'Food & Drink',
      views: '240k views',
      date: '4 months ago',
      duration: '7:36',
      imgSrc: './images/food1.png',
      link: '/',
    },
    {
      title: 'Advertising Outdoors',
      author: 'Food & Drink',
      views: '13k views',
      date: '15 days ago',
      duration: '2:19',
      imgSrc: './images/food2.png',
      link: '/',
    },
    {
      title: 'Radio Astronomy',
      author: 'Food & Drink',
      views: '1k views',
      date: '11 months ago',
      duration: '9:05',
      imgSrc: './images/food3.png',
      link: '/',
    },
    {
      title: 'A Good Autoresponder',
      author: 'Food & Drink',
      views: '45k views',
      date: '2 months ago',
      duration: '3:40',
      imgSrc: './images/food4.png',
      link: '/',
    },
    {
      title: 'Baby Monitor Technology',
      author: 'Food & Drink',
      views: '86k views',
      date: '7 days ago',
      duration: '1:56',
      imgSrc: './images/food5.png',
      link: '/',
    },
    {
      title: 'Asteroids',
      author: 'Food & Drink',
      views: '123k views',
      date: '4 months ago',
      duration: '6:12',
      imgSrc: './images/food6.png',
      link: '/',
    },
  ],
}

export default foodAndDrinkAuthor
