const margaretPhelpsAuthor = {
  name: 'Margaret Phelps',
  avatar: './avatars/user3.png',
  link: '/',
  subscribers: '1.2m',
  feed: [
    {
      title: 'Astronomy Or Astrology',
      author: 'Margaret Phelps',
      views: '240k views',
      date: '4 months ago',
      duration: '7:36',
      imgSrc: './images/margo1.png',
      link: '/',
    },
    {
      title: 'Advertising Outdoors',
      author: 'Margaret Phelps',
      views: '13k views',
      date: '15 days ago',
      duration: '2:19',
      imgSrc: './images/margo2.png',
      link: '/',
    },
    {
      title: 'Radio Astronomy',
      author: 'Margaret Phelps',
      views: '1k views',
      date: '11 months ago',
      duration: '9:05',
      imgSrc: './images/margo3.png',
      link: '/',
    },
    {
      title: 'A Good Autoresponder',
      author: 'Margaret Phelps',
      views: '45k views',
      date: '2 months ago',
      duration: '3:40',
      imgSrc: './images/margo4.png',
      link: '/',
    },
    {
      title: 'Baby Monitor Technology',
      author: 'Margaret Phelps',
      views: '86k views',
      date: '7 days ago',
      duration: '1:56',
      imgSrc: './images/margo5.png',
      link: '/',
    },
    {
      title: 'Asteroids',
      author: 'Margaret Phelps',
      views: '123k views',
      date: '4 months ago',
      duration: '4:12',
      imgSrc: './images/margo6.png',
      link: '/',
    },
  ],
}

export default margaretPhelpsAuthor
